name: Build

on:
  push:
    branches:
      - "**"
    paths:
      - "Source/**"

jobs:
  build-node:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Yarn install
        run: yarn

      - name: Build
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn ci


  build-dotnet:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.102'
      - name: Build .NET
        run: dotnet build --configuration Release
      - name: Test .NET
        run: dotnet test --configuration Release --no-build
